name: akar_icons_flutter
description: Perfectly rounded icon library made for designers and developers.
version: 1.1.9
homepage: https://github.com/alann-maulana/akar_icons_flutter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family:  AkarIcons
      fonts:
        - asset: fonts/AkarIcons.ttf
